version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docusaurus_web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docusaurus.rule=Host(`docs.vandenbrinksoftware.com`)"
      - "traefik.http.routers.docusaurus.entrypoints=websecure"
      - "traefik.http.routers.docusaurus.tls=true"
      - "traefik.http.routers.docusaurus.tls.certresolver=myresolver"
      - "traefik.http.services.docusaurus.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    networks:
      - web

networks:
  web:
    external: true
